In [2]:
list=[1,2,3,4,5]
list


[1, 2, 3, 4, 5]

In [3]:
type(list)

list

In [4]:
import numpy as np
arr=np.array(list)

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr_2d=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(arr_2d)
print(ar)
ar

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(ar)

numpy.ndarray

In [8]:
arr.shape


(5,)

In [9]:
ar.shape

(3, 3)

In [11]:
ar.ndim

2

In [12]:
arr.ndim

1

In [13]:
ar.dtype

dtype('int32')

In [14]:
arr.dtype

dtype('int32')

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((3,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [2]:
import numpy as np
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones((3,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]
arr=np.array([l1,l2,l3])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.shape

(3, 3)

In [13]:
arr
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr1=[1,2,3,4,5,6,7,8,9]
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
arr1[0]

1

In [18]:
print(arr1[1])
arr1[8]

2


9

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[:,:1]

array([[1],
       [4],
       [7]])

In [22]:
arr[:,3:]

array([], shape=(3, 0), dtype=int32)

In [23]:
arr[:,2:]

array([[3],
       [6],
       [9]])

In [24]:
arr[2:,:]

array([[7, 8, 9]])

In [25]:
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
arr1[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
arr1[2:10]

[3, 4, 5, 6, 7, 8, 9]

In [28]:
arr1[:8]

[1, 2, 3, 4, 5, 6, 7, 8]

In [29]:
arr1[8:]

[9]

In [30]:
arr1[-9:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
arr1[-9:-5]

[1, 2, 3, 4]

In [34]:
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
arr1[ :3] 

[1, 2, 3]

In [38]:
arr1[3]=100


In [39]:
arr1

[1, 2, 3, 100, 5, 6, 7, 8, 9]

In [47]:
arr1[:6]=1000   #

TypeError: can only assign an iterable

In [46]:
arr1[arr1>5]                       #


TypeError: '>' not supported between instances of 'list' and 'int'

In [48]:
l=np.array([1,2,3,4,5,6])
l

array([1, 2, 3, 4, 5, 6])

In [49]:
l[:3]=100

In [50]:
l

array([100, 100, 100,   4,   5,   6])

In [51]:
l[l>4]

array([100, 100, 100,   5,   6])

In [52]:
l[l<1]

array([], dtype=int32)

In [53]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [55]:
arr1=np.arange(1,11).reshape(5,2)
arr2=np.arange(1,11).reshape(5,2)
arr1*arr2


array([[  1,   4],
       [  9,  16],
       [ 25,  36],
       [ 49,  64],
       [ 81, 100]])

In [56]:
np.linspace(1,100,10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [63]:
np.linspace(1,1000,10)

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.random.rand(2)

array([0.26376852, 0.22751295])

In [66]:
np.random.rand(2)

array([0.32918298, 0.16327216])

In [67]:
np.random.randn(2)

array([ 0.6391084 , -0.70382505])

In [68]:
np.random.randn(2)

array([-0.64043494,  0.54587425])

In [69]:
np.random.rand(3,3)

array([[0.29015552, 0.20133584, 0.45302152],
       [0.31445347, 0.30858173, 0.44940213],
       [0.93018434, 0.27024796, 0.69743594]])

In [70]:
np.random.randn(4,4)

array([[-0.75591871,  0.46205976,  0.78898281, -0.11303872],
       [-0.50280642, -0.26180746,  1.62066806, -0.15408639],
       [ 0.18882312, -0.69653357, -1.82383986, -0.27984354],
       [-0.75019691, -0.10999387, -0.0038954 , -0.57843402]])

In [71]:
np.random.randn(4,4)

array([[-1.63921406,  0.35993851, -1.35438195, -0.36791106],
       [ 0.57226753, -0.88964423,  1.0426974 ,  0.14979946],
       [-0.24013709,  0.30533626, -0.2806809 , -0.33381322],
       [ 1.2599816 ,  1.66559597, -0.3815474 ,  0.19760216]])

In [72]:
np.random.rand(9).reshape(3,3)

array([[0.23823808, 0.50697389, 0.73523779],
       [0.52006773, 0.60962294, 0.0667494 ],
       [0.29819813, 0.84899626, 0.80132903]])

In [73]:
np.random.randn(9).reshape(3,3)

array([[-0.26927751,  0.47107027, -0.02982054],
       [ 1.1151085 ,  0.71623242,  0.53030479],
       [ 1.20480478, -0.34379461, -0.01288632]])

In [79]:
np.random.randint(3)

0

In [80]:
np.random.randint(3)

2

In [90]:
np.random.randint(3)

1

In [136]:
a=np.random.randint(0,9,2)
b=np.random.randint(0,9)
print(a)
print(b)
type(b)



[7 3]
3


int

In [137]:
type(a)

numpy.ndarray

In [107]:
np.random.randint(0,9,12)

array([5, 4, 4, 0, 2, 1, 0, 4, 7, 1, 5, 6])

In [111]:
np.random.randint(0,9,49).reshape(7,7)

array([[6, 7, 0, 6, 1, 8, 2],
       [8, 7, 7, 8, 2, 4, 5],
       [8, 0, 8, 6, 4, 1, 8],
       [6, 8, 5, 8, 2, 2, 2],
       [4, 2, 8, 6, 7, 5, 8],
       [8, 2, 4, 5, 8, 0, 7],
       [6, 5, 5, 0, 5, 3, 2]])

In [114]:
np.random.randint(1,5,10).reshape(2,5)

array([[2, 4, 4, 2, 2],
       [3, 2, 4, 3, 2]])

In [115]:
np.random.random_sample((1,5))

array([[0.76131194, 0.45990511, 0.29374217, 0.25555249, 0.56194376]])

In [128]:
np.random.random_sample((5,2))

array([[0.29211312, 0.39775274],
       [0.85127891, 0.17366905],
       [0.10059239, 0.04281231],
       [0.28680082, 0.30364472],
       [0.32954796, 0.91325086]])

In [139]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)

In [140]:
print(a)

[1 2 3 4 5 6]


In [141]:
print(b)

[[1 2 3]
 [4 5 6]]


In [142]:
a

array([1, 2, 3, 4, 5, 6])

In [143]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
a.ndim

1

In [145]:
b.ndim

2

In [146]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [147]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
arr1=np.arange(1,10)

In [149]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
arr[0]

1

In [155]:
b=arr.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [153]:
arr[1]

2

In [156]:
b[1][1]

5

In [157]:
arr[:3]=100

In [158]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [159]:
b[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [160]:
b>8

array([[ True,  True,  True],
       [False, False, False],
       [False, False,  True]])

In [161]:
b<8

array([[False, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [162]:
b

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [163]:
b[b<8]

array([4, 5, 6, 7])

In [164]:
b[b>8]

array([100, 100, 100,   9])

In [165]:
b==100

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [166]:
b

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [167]:
b.shape

(3, 3)

In [168]:
b+3

array([[103, 103, 103],
       [  7,   8,   9],
       [ 10,  11,  12]])

In [172]:
a=np.array([10,10,10])

In [173]:
a

array([10, 10, 10])

In [174]:
a+b

array([[110, 110, 110],
       [ 14,  15,  16],
       [ 17,  18,  19]])

In [175]:
a*b

array([[1000, 1000, 1000],
       [  40,   50,   60],
       [  70,   80,   90]])

In [176]:
a

array([10, 10, 10])

In [177]:
b

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [178]:
c=np.arange(0,9).reshape(3,3)

In [179]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [180]:
b+c

array([[100, 101, 102],
       [  7,   9,  11],
       [ 13,  15,  17]])

In [181]:
d=c
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [182]:
arr=np.arange(0,9)

In [183]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [184]:
arr.min()

0

In [185]:
arr.max()

8

In [186]:
arr.argmin()

0

In [187]:
arr.argmax()

8

In [188]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [189]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [190]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

In [191]:
arr.mean()

4.0

In [194]:
arr=np.arange(0,16)
arr2d=arr.reshape(4,4)

arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [195]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [196]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [197]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [198]:
arr2d.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [199]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,22,33],[44,55,66]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [200]:
c=np.concatenate((a,b),axis=1)
c

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [202]:
d=np.concatenate((a,b),axis=0)
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [203]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [204]:
b

array([[11, 22, 33],
       [44, 55, 66]])

In [205]:
np.hsplit(a,2)

ValueError: array split does not result in an equal division

In [206]:
c=np.arange(0,16).reshape(4,4)

In [207]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [208]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [209]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [210]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [211]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [213]:
import pandas as pd

a=pd.Series([1,2,3,4],index=["a","b","c","d"])
print(a)

a    1
b    2
c    3
d    4
dtype: int64


In [215]:
country=["INDIA","USA","ENGLAND"]
capital=["DELHI","WASHINGTON DC","LONDON"]
b=np.array(capital)
b


array(['DELHI', 'WASHINGTON DC', 'LONDON'], dtype='<U13')

In [217]:
c=pd.Series(b)
c

0            DELHI
1    WASHINGTON DC
2           LONDON
dtype: object

In [219]:
d=pd.Series(data=capital)
d

0            DELHI
1    WASHINGTON DC
2           LONDON
dtype: object

In [220]:
d=pd.Series(capital,index=country)

In [221]:
d

INDIA              DELHI
USA        WASHINGTON DC
ENGLAND           LONDON
dtype: object

In [222]:
pd.Series(data=capital,index=country)

INDIA              DELHI
USA        WASHINGTON DC
ENGLAND           LONDON
dtype: object

In [239]:
pd.Series(capital,country)

INDIA              DELHI
USA        WASHINGTON DC
ENGLAND           LONDON
dtype: object

In [242]:
b

'WASHINGTON DC'

In [225]:
pd.Series(b)

0            DELHI
1    WASHINGTON DC
2           LONDON
dtype: object

In [227]:
dic={"a":10,"b":20,"c":40,"d":40}
c=pd.Series(dic)
c

a    10
b    20
c    40
d    40
dtype: int64

In [228]:
c.shape

(4,)

In [229]:
c[1]

20

In [230]:
c[0]

10

In [232]:
c[3]

40

In [233]:
c[:2]

a    10
b    20
dtype: int64

In [234]:
c[0]

10

In [235]:
c[:]

a    10
b    20
c    40
d    40
dtype: int64

In [236]:
country

['INDIA', 'USA', 'ENGLAND']

In [237]:
country[1]

'USA'

In [238]:
country[:]

['INDIA', 'USA', 'ENGLAND']

In [243]:
c

a    10
b    20
c    40
d    40
dtype: int64

In [244]:
c["a"]

10

In [245]:
c[["a","b","c"]]

a    10
b    20
c    40
dtype: int64

In [248]:
print(c)
c+c

a    10
b    20
c    40
d    40
dtype: int64


a    20
b    40
c    80
d    80
dtype: int64

In [249]:
data={"country":["india","france","england"], "capital":["delhi","paris","london"],"population":[100,50,30]}
df=pd.DataFrame(data,columns=["country","capital","population"])


In [250]:
df

country capital  population
0    india   delhi         100
1   france   paris          50
2  england  london          30

In [258]:
c=pd.DataFrame(data)

In [260]:
c

country capital  population
0    india   delhi         100
1   france   paris          50
2  england  london          30

In [253]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [255]:
a=["apple","banana","coconut","dates"]
df=pd.DataFrame(a,columns=["fruits"])
df

fruits
0    apple
1   banana
2  coconut
3    dates

In [256]:
df=pd.DataFrame(a)
df

0
0    apple
1   banana
2  coconut
3    dates

In [2]:
import pandas as pd

In [3]:
people=[["ram",26,"o+"],["sam",28,"ab+"],["chandu",30,"o-"]]
df=pd.DataFrame(people,columns=["NAMES","AGE","BLOODGROUP"])
df

NAMES  AGE BLOODGROUP
0     ram   26         o+
1     sam   28        ab+
2  chandu   30         o-

In [4]:
people={"NAMES":["RAM","SAM","TOM","NAGA"],"AGE":[20,30,25,29],"BGROUP":["A","B+","O+","O-"]}
df=pd.DataFrame(people)
df

NAMES  AGE BGROUP
0   RAM   20      A
1   SAM   30     B+
2   TOM   25     O+
3  NAGA   29     O-

In [8]:
csv_df=pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.csv")
csv_df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [11]:
json_df=pd.read_json("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.json")
json_df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [12]:
excel_df=pd.read_excel("https://github.com/insaid2018/Term-1/blob/master/Data/Casestudy/supermarkets.xlsx?raw=true")
excel_df

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [13]:
e=pd.read_excel("https://github.com/insaid2018/Term-1/blob/master/Data/Casestudy/supermarkets.xlsx?raw=true",sheet_name=0)
e

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [14]:
csv_df=pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets-semi-colons.txt")
csv_df

ID;Address;City;State;Country;Name;Employees
0  1;3666 21st St;San Francisco;CA 94114;USA;Made...
1  2;735 Dolores St;San Francisco;CA 94119;USA;Br...
2  3;332 Hill St;San Francisco;California 94114;U...
3  4;3995 23rd St;San Francisco;CA 94114;USA;Ben'...
4  5;1056 Sanchez St;San Francisco;California;USA...
5  6;551 Alvarado St;San Francisco;CA 94114;USA;R...

In [15]:
a=pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets-semi-colons.txt",sep=";")
a

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [17]:
people

{'NAMES': ['RAM', 'SAM', 'TOM', 'NAGA'],
 'AGE': [20, 30, 25, 29],
 'BGROUP': ['A', 'B+', 'O+', 'O-']}

In [18]:
df

NAMES  AGE BGROUP
0   RAM   20      A
1   SAM   30     B+
2   TOM   25     O+
3  NAGA   29     O-

In [19]:
df.shape

(4, 3)

In [20]:
print(df.dtypes)

NAMES     object
AGE        int64
BGROUP    object
dtype: object


In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   NAMES   4 non-null      object
 1   AGE     4 non-null      int64 
 2   BGROUP  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [22]:
df.count()

NAMES     4
AGE       4
BGROUP    4
dtype: int64

In [23]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
df.columns

Index(['NAMES', 'AGE', 'BGROUP'], dtype='object')

In [25]:
new_df=df.set_index("NAMES")
new_df

AGE BGROUP
NAMES            
RAM     20      A
SAM     30     B+
TOM     25     O+
NAGA    29     O-

In [26]:
df

NAMES  AGE BGROUP
0   RAM   20      A
1   SAM   30     B+
2   TOM   25     O+
3  NAGA   29     O-

In [27]:
df["BGROUP"]

0     A
1    B+
2    O+
3    O-
Name: BGROUP, dtype: object

In [28]:
df["SCORE"]=[11,22,33,44]
df

NAMES  AGE BGROUP  SCORE
0   RAM   20      A     11
1   SAM   30     B+     22
2   TOM   25     O+     33
3  NAGA   29     O-     44

In [40]:
df["sum"]=df["AGE"]+df["SCORE"]
df

NAMES  AGE BGROUP  SCORE  sum
0   RAM   20      A     11   31
1   SAM   30     B+     22   52
2   TOM   25     O+     33   58
3  NAGA   29     O-     44   73

In [41]:
df.drop('sum', axis=1, inplace=True)
df


NAMES  AGE BGROUP  SCORE
0   RAM   20      A     11
1   SAM   30     B+     22
2   TOM   25     O+     33
3  NAGA   29     O-     44

In [42]:
del df['SCORE']
df

NAMES  AGE BGROUP
0   RAM   20      A
1   SAM   30     B+
2   TOM   25     O+
3  NAGA   29     O-

In [44]:
ndf=df.set_index("NAMES")
ndf

AGE BGROUP
NAMES            
RAM     20      A
SAM     30     B+
TOM     25     O+
NAGA    29     O-

In [66]:
df["num"]=[1,2,3,4]
df

NAMES  AGE BGROUP  num
0   RAM   20      A    1
1   SAM   30     B+    2
2   TOM   25     O+    3
3  NAGA   29     O-    4

In [67]:
df.drop("num",axis=1,inplace=True)
df

NAMES  AGE BGROUP
0   RAM   20      A
1   SAM   30     B+
2   TOM   25     O+
3  NAGA   29     O-

In [68]:
df

NAMES  AGE BGROUP
0   RAM   20      A
1   SAM   30     B+
2   TOM   25     O+
3  NAGA   29     O-

In [49]:
df["num"]=[1,2,3,4]
df

NAMES  AGE BGROUP  num
0   RAM   20      A    1
1   SAM   30     B+    2
2   TOM   25     O+    3
3  NAGA   29     O-    4

In [58]:
df.drop(["num"],1)


<ipython-input-58-62df800f53e6>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df.drop(["num"],1)


NAMES  AGE BGROUP
0   RAM   20      A
1   SAM   30     B+
2   TOM   25     O+
3  NAGA   29     O-

In [53]:
ndf

AGE BGROUP
NAMES            
RAM     20      A
SAM     30     B+
TOM     25     O+
NAGA    29     O-

In [62]:
ndf.drop("TOM",axis=0)


AGE BGROUP
NAMES            
RAM     20      A
SAM     30     B+
NAGA    29     O-

In [63]:
ndf

AGE BGROUP
NAMES            
RAM     20      A
SAM     30     B+
TOM     25     O+
NAGA    29     O-

In [70]:
market_df = pd.read_csv('http://pythonhow.com/supermarkets.csv')
market_df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [75]:
market=market_df.set_index("ID")
market

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [72]:
market_df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [77]:
market.iloc[0:4,0:5]

Address           City             State Country         Name
ID                                                                      
1     3666 21st St  San Francisco          CA 94114     USA      Madeira
2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop
3      332 Hill St  San Francisco  California 94114     USA  Super River
4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop

In [86]:
market.iloc[4:,0:2]

Address           City
ID                                
5   1056 Sanchez St  San Francisco
6   551 Alvarado St  San Francisco

In [79]:
market.iloc[:,:]

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [90]:
market.loc[4:5,"Address"]

ID
4       3995 23rd St
5    1056 Sanchez St
Name: Address, dtype: object

In [95]:
market.loc[1:4,"Address":"Country"]

Address           City             State Country
ID                                                         
1     3666 21st St  San Francisco          CA 94114     USA
2   735 Dolores St  San Francisco          CA 94119     USA
3      332 Hill St  San Francisco  California 94114     USA
4     3995 23rd St  San Francisco          CA 94114     USA

In [98]:
market.loc[:,"State":]

State Country         Name  Employees
ID                                                  
1           CA 94114     USA      Madeira          8
2           CA 94119     USA  Bready Shop         15
3   California 94114     USA  Super River         25
4           CA 94114     USA   Ben's Shop         10
5         California     USA      Sanchez         12
6           CA 94114     USA   Richvalley         20

In [99]:
df1=pd.DataFrame({"id":[1,2,3,4,5],
                 "name":["a","b","c","d","e"],
                 "sub":["sub1","sub2","sub3","sub4","sub5"]})
df2=pd.DataFrame({"id":[1,2,3,4,5],
                 "name":["b","c","d","e","f"],
                 "sub":["sub3","sub4","sub5","sub6","sub7"]})

In [101]:
print(df1)
df2

   id name   sub
0   1    a  sub1
1   2    b  sub2
2   3    c  sub3
3   4    d  sub4
4   5    e  sub5


id name   sub
0   1    b  sub3
1   2    c  sub4
2   3    d  sub5
3   4    e  sub6
4   5    f  sub7

In [102]:
pd.concat([df1,df2],axis=0)

id name   sub
0   1    a  sub1
1   2    b  sub2
2   3    c  sub3
3   4    d  sub4
4   5    e  sub5
0   1    b  sub3
1   2    c  sub4
2   3    d  sub5
3   4    e  sub6
4   5    f  sub7

In [103]:
pd.concat([df1,df2],axis=1)

id name   sub  id name   sub
0   1    a  sub1   1    b  sub3
1   2    b  sub2   2    c  sub4
2   3    c  sub3   3    d  sub5
3   4    d  sub4   4    e  sub6
4   5    e  sub5   5    f  sub7

In [110]:
pd.merge(left=df1, right=df2, on="sub")

id_x name_x   sub  id_y name_y
0     3      c  sub3     1      b
1     4      d  sub4     2      c
2     5      e  sub5     3      d

In [111]:
pd.merge(left=df1,right=df2,on='id')

id name_x sub_x name_y sub_y
0   1      a  sub1      b  sub3
1   2      b  sub2      c  sub4
2   3      c  sub3      d  sub5
3   4      d  sub4      e  sub6
4   5      e  sub5      f  sub7

In [113]:
df3=pd.DataFrame({"id":[100],"name":["john"],"sub":["sub100"]})
df3


id  name     sub
0  100  john  sub100

In [114]:
df1


id name   sub
0   1    a  sub1
1   2    b  sub2
2   3    c  sub3
3   4    d  sub4
4   5    e  sub5

In [115]:
df4=df1
df5=df3
df4.append(df5)

id  name     sub
0    1     a    sub1
1    2     b    sub2
2    3     c    sub3
3    4     d    sub4
4    5     e    sub5
0  100  john  sub100

In [119]:
df4=df1
df5=df3
df4.append(df5,ignore_index=True)


id  name     sub
0    1     a    sub1
1    2     b    sub2
2    3     c    sub3
3    4     d    sub4
4    5     e    sub5
5  100  john  sub100

In [120]:
market

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [121]:
market["Employees"]>=15

ID
1    False
2     True
3     True
4    False
5    False
6     True
Name: Employees, dtype: bool

In [122]:
market[market["Employees"]>=15]

Address           City             State Country         Name  \
ID                                                                          
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
2          15  
3          25  
6          20

In [124]:
market[(market["Employees"]>=15)&(market["State"]!="CA94119")]

Address           City             State Country         Name  \
ID                                                                          
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
2          15  
3          25  
6          20

In [158]:
company=["a","a","a","b","b","b"]
year=[2001,2002,2003,2001,2002,2003]
Revenue=[100,200,300,400,500,600]
Employee=[11,22,33,44,55,66]


In [152]:
list(zip(Revenue,Employee))

[(100, 11), (200, 22), (300, 33), (400, 44), (500, 55), (600, 66)]

In [159]:
list(zip(company,year))

[('a', 2001), ('a', 2002), ('a', 2003), ('b', 2001), ('b', 2002), ('b', 2003)]

In [160]:
hier_index=list(zip(company,year))

In [164]:

hier_index=pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('a', 2001),
            ('a', 2002),
            ('a', 2003),
            ('b', 2001),
            ('b', 2002),
            ('b', 2003)],
           )

In [162]:
ddf=pd.DataFrame(data=list(zip(Revenue,Employee)), index=hier_index, columns=["revenue","employee"])
ddf

revenue  employee
a 2001      100        11
  2002      200        22
  2003      300        33
b 2001      400        44
  2002      500        55
  2003      600        66

In [177]:
ddf.index.names=["company","year"]
ddf

revenue  employee
company year                   
a       2001      100        11
        2002      200        22
        2003      300        33
b       2001      400        44
        2002      500        55
        2003      600        66

In [165]:
multidf = pd.DataFrame(data = list(zip(Revenue, Employee)),  columns=['Revenue','Employee'])
multidf

Revenue  Employee
0      100        11
1      200        22
2      300        33
3      400        44
4      500        55
5      600        66

In [178]:
ddf

revenue  employee
company year                   
a       2001      100        11
        2002      200        22
        2003      300        33
b       2001      400        44
        2002      500        55
        2003      600        66

In [167]:
ddf.loc['a']

revenue  employee
2001      100        11
2002      200        22
2003      300        33

In [168]:
ddf.loc['a'].loc[2003]

revenue     300
employee     33
Name: 2003, dtype: int64

In [179]:
ddf.xs('a',level="company")

revenue  employee
year                   
2001      100        11
2002      200        22
2003      300        33

In [172]:
ddf.xs("b")

revenue  employee
2001      400        44
2002      500        55
2003      600        66

In [180]:
ddf.xs(2002,level="year")

revenue  employee
company                   
a            200        22
b            500        55

In [5]:
import seaborn as sns
tips=sns.load_dataset("tips")
tips.head()


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
tips.shape

(244, 7)

In [7]:
tips.index

RangeIndex(start=0, stop=244, step=1)

In [8]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
tip=tips.head(10)

In [10]:
tip

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [13]:
tip.set_index(["sex"])

total_bill   tip smoker  day    time  size
sex                                               
Female       16.99  1.01     No  Sun  Dinner     2
Male         10.34  1.66     No  Sun  Dinner     3
Male         21.01  3.50     No  Sun  Dinner     3
Male         23.68  3.31     No  Sun  Dinner     2
Female       24.59  3.61     No  Sun  Dinner     4
Male         25.29  4.71     No  Sun  Dinner     4
Male          8.77  2.00     No  Sun  Dinner     2
Male         26.88  3.12     No  Sun  Dinner     4
Male         15.04  1.96     No  Sun  Dinner     2
Male         14.78  3.23     No  Sun  Dinner     2

In [23]:
multiindex_tip=tip.set_index(["sex","size"])

In [24]:
multiindex_tip


total_bill   tip smoker  day    time
sex    size                                      
Female 2          16.99  1.01     No  Sun  Dinner
Male   3          10.34  1.66     No  Sun  Dinner
       3          21.01  3.50     No  Sun  Dinner
       2          23.68  3.31     No  Sun  Dinner
Female 4          24.59  3.61     No  Sun  Dinner
Male   4          25.29  4.71     No  Sun  Dinner
       2           8.77  2.00     No  Sun  Dinner
       4          26.88  3.12     No  Sun  Dinner
       2          15.04  1.96     No  Sun  Dinner
       2          14.78  3.23     No  Sun  Dinner

In [28]:
multiindex_tip.sort_index(inplace=True)

In [29]:
multiindex_tip

total_bill   tip smoker  day    time
sex    size                                      
Male   2          23.68  3.31     No  Sun  Dinner
       2           8.77  2.00     No  Sun  Dinner
       2          15.04  1.96     No  Sun  Dinner
       2          14.78  3.23     No  Sun  Dinner
       3          10.34  1.66     No  Sun  Dinner
       3          21.01  3.50     No  Sun  Dinner
       4          25.29  4.71     No  Sun  Dinner
       4          26.88  3.12     No  Sun  Dinner
Female 2          16.99  1.01     No  Sun  Dinner
       4          24.59  3.61     No  Sun  Dinner

In [31]:
multiindex_tip.loc["Male"]

total_bill   tip smoker  day    time
size                                      
2          23.68  3.31     No  Sun  Dinner
2           8.77  2.00     No  Sun  Dinner
2          15.04  1.96     No  Sun  Dinner
2          14.78  3.23     No  Sun  Dinner
3          10.34  1.66     No  Sun  Dinner
3          21.01  3.50     No  Sun  Dinner
4          25.29  4.71     No  Sun  Dinner
4          26.88  3.12     No  Sun  Dinner

In [32]:
multiindex_tip.xs(2 , level="size")

total_bill   tip smoker  day    time
sex                                         
Male         23.68  3.31     No  Sun  Dinner
Male          8.77  2.00     No  Sun  Dinner
Male         15.04  1.96     No  Sun  Dinner
Male         14.78  3.23     No  Sun  Dinner
Female       16.99  1.01     No  Sun  Dinner

In [33]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [34]:
bytime=tips.groupby("time")

In [35]:
bytime

In [36]:
for i in bytime:
    print(i)

('Lunch',      total_bill   tip     sex smoker   day   time  size
77        27.20  4.00    Male     No  Thur  Lunch     4
78        22.76  3.00    Male     No  Thur  Lunch     2
79        17.29  2.71    Male     No  Thur  Lunch     2
80        19.44  3.00    Male    Yes  Thur  Lunch     2
81        16.66  3.40    Male     No  Thur  Lunch     2
..          ...   ...     ...    ...   ...    ...   ...
222        8.58  1.92    Male    Yes   Fri  Lunch     1
223       15.98  3.00  Female     No   Fri  Lunch     3
224       13.42  1.58    Male    Yes   Fri  Lunch     2
225       16.27  2.50  Female    Yes   Fri  Lunch     2
226       10.09  2.00  Female    Yes   Fri  Lunch     2

[68 rows x 7 columns])
('Dinner',      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     

In [37]:
bytime.count()

total_bill  tip  sex  smoker  day  size
time                                           
Lunch           68   68   68      68   68    68
Dinner         176  176  176     176  176   176

In [39]:
bytime.mean()

total_bill       tip      size
time                                  
Lunch    17.168676  2.728088  2.411765
Dinner   20.797159  3.102670  2.630682

In [40]:
bytime.sum()

total_bill     tip  size
time                            
Lunch      1167.47  185.51   164
Dinner     3660.30  546.07   463

In [41]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [42]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [43]:
tips["size"]

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [44]:
tips["size"].unique()

array([2, 3, 4, 1, 6, 5], dtype=int64)

In [45]:
tips["size"].nunique()

6

In [46]:
tips["size"].value_counts()

2    156
3     38
4     37
5      5
1      4
6      4
Name: size, dtype: int64

In [48]:
import pandas as pd
people=[["ramu",100,"o+"],["john",200,"AB+"],["sam",1000,"o-"],["chandu",10,"A+"]]
people_df=pd.DataFrame(people , columns=["Names","Score","BloodGroup"])
people_df

Names  Score BloodGroup
0    ramu    100         o+
1    john    200        AB+
2     sam   1000         o-
3  chandu     10         A+

In [49]:
def value(x):
    return x+x+x


In [51]:
people_df["Score"].apply(value)

0     300
1     600
2    3000
3      30
Name: Score, dtype: int64

In [53]:
people_df["Score"].apply(lambda x:x+x)

0     200
1     400
2    2000
3      20
Name: Score, dtype: int64

In [54]:
people_df

Names  Score BloodGroup
0    ramu    100         o+
1    john    200        AB+
2     sam   1000         o-
3  chandu     10         A+

In [55]:
people_df.sort_values("Score")

Names  Score BloodGroup
3  chandu     10         A+
0    ramu    100         o+
1    john    200        AB+
2     sam   1000         o-

In [56]:
air_df=pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/AirQualityUCI.csv")

In [57]:
air_df

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     3/10/2004  18:00:00     2.6         1360       150      11.9   
1     3/10/2004  19:00:00     2.0         1292       112       9.4   
2     3/10/2004  20:00:00     2.2         1402        88       9.0   
3     3/10/2004  21:00:00     2.2         1376        80       9.2   
4     3/10/2004  22:00:00     1.6         1272        51       6.5   
...         ...       ...     ...          ...       ...       ...   
9352   4/4/2005  10:00:00     3.1         1314      -200      13.5   
9353   4/4/2005  11:00:00     2.4         1163      -200      11.4   
9354   4/4/2005  12:00:00     2.4         1142      -200      12.4   
9355   4/4/2005  13:00:00     2.1         1003      -200       9.5   
9356   4/4/2005  14:00:00     2.2         1071      -200      11.9   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0              1046      166          1056      113          1692   
1               955      103          1174       92          1559   
2               939      131          1140      114          1555   
3               948      172          1092      122          1584   
4               836      131          1205      116          1490   
...             ...      ...           ...      ...           ...   
9352           1101      472           539      190          1374   
9353           1027      353           604      179          1264   
9354           1063      293           603      175          1241   
9355            961      235           702      156          1041   
9356           1047      265           654      168          1129   

      PT08.S5(O3)     T    RH      AH  
0            1268  13.6  48.9  0.7578  
1             972  13.3  47.7  0.7255  
2            1074  11.9  54.0  0.7502  
3            1203  11.0  60.0  0.7867  
4            1110  11.2  59.6  0.7888  
...           ...   ...   ...     ...  
9352         1729  21.9  29.3  0.7568  
9353         1269  24.3  23.7  0.7119  
9354         1092  26.9  18.3  0.6406  
9355          770  28.3  13.5  0.5139  
9356          816  28.5  13.1  0.5028  

[9357 rows x 15 columns]

In [61]:
air_df.describe(include="all")

Date      Time       CO(GT)  PT08.S1(CO)     NMHC(GT)  \
count        9357      9357  9357.000000  9357.000000  9357.000000   
unique        391        24          NaN          NaN          NaN   
top     9/21/2004  18:00:00          NaN          NaN          NaN   
freq           24       390          NaN          NaN          NaN   
mean          NaN       NaN   -34.207524  1048.990061  -159.090093   
std           NaN       NaN    77.657170   329.832710   139.789093   
min           NaN       NaN  -200.000000  -200.000000  -200.000000   
25%           NaN       NaN     0.600000   921.000000  -200.000000   
50%           NaN       NaN     1.500000  1053.000000  -200.000000   
75%           NaN       NaN     2.600000  1221.000000  -200.000000   
max           NaN       NaN    11.900000  2040.000000  1189.000000   

           C6H6(GT)  PT08.S2(NMHC)      NOx(GT)  PT08.S3(NOx)      NO2(GT)  \
count   9357.000000    9357.000000  9357.000000   9357.000000  9357.000000   
unique          NaN            NaN          NaN           NaN          NaN   
top             NaN            NaN          NaN           NaN          NaN   
freq            NaN            NaN          NaN           NaN          NaN   
mean       1.865683     894.595276   168.616971    794.990168    58.148873   
std       41.380206     342.333252   257.433866    321.993552   126.940455   
min     -200.000000    -200.000000  -200.000000   -200.000000  -200.000000   
25%        4.000000     711.000000    50.000000    637.000000    53.000000   
50%        7.900000     895.000000   141.000000    794.000000    96.000000   
75%       13.600000    1105.000000   284.000000    960.000000   133.000000   
max       63.700000    2214.000000  1479.000000   2683.000000   340.000000   

        PT08.S4(NO2)  PT08.S5(O3)            T           RH           AH  
count    9357.000000  9357.000000  9357.000000  9357.000000  9357.000000  
unique           NaN          NaN          NaN          NaN          NaN  
top              NaN          NaN          NaN          NaN          NaN  
freq             NaN          NaN          NaN          NaN          NaN  
mean     1391.479641   975.072032     9.778305    39.485380    -6.837604  
std       467.210125   456.938184    43.203623    51.216145    38.976670  
min      -200.000000  -200.000000  -200.000000  -200.000000  -200.000000  
25%      1185.000000   700.000000    10.900000    34.100000     0.692300  
50%      1446.000000   942.000000    17.200000    48.600000     0.976800  
75%      1662.000000  1255.000000    24.100000    61.900000     1.296200  
max      2775.000000  2523.000000    44.600000    88.700000     2.231000

In [62]:
air_df.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  3/10/2004  18:00:00     2.6         1360       150      11.9   
1  3/10/2004  19:00:00     2.0         1292       112       9.4   
2  3/10/2004  20:00:00     2.2         1402        88       9.0   
3  3/10/2004  21:00:00     2.2         1376        80       9.2   
4  3/10/2004  22:00:00     1.6         1272        51       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0           1046      166          1056      113          1692         1268   
1            955      103          1174       92          1559          972   
2            939      131          1140      114          1555         1074   
3            948      172          1092      122          1584         1203   
4            836      131          1205      116          1490         1110   

      T    RH      AH  
0  13.6  48.9  0.7578  
1  13.3  47.7  0.7255  
2  11.9  54.0  0.7502  
3  11.0  60.0  0.7867  
4  11.2  59.6  0.7888

In [70]:
air_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           9357 non-null   object 
 1   Time           9357 non-null   object 
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   int64  
 4   NMHC(GT)       9357 non-null   int64  
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   int64  
 7   NOx(GT)        9357 non-null   int64  
 8   PT08.S3(NOx)   9357 non-null   int64  
 9   NO2(GT)        9357 non-null   int64  
 10  PT08.S4(NO2)   9357 non-null   int64  
 11  PT08.S5(O3)    9357 non-null   int64  
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: float64(5), int64(8), object(2)
memory usage: 1.1+ MB


In [74]:
import pandas as pd
air_df['Date']=pd.to_datetime(air_df['Date'], format='%m/%d/%y')

In [90]:
import pandas as pd
air_df['Date'] = pd.to_datetime(air_df['Date'],format="%dd/%mm/%yy" )    

In [91]:
air_df["Date"]

0      2004-03-10
1      2004-03-10
2      2004-03-10
3      2004-03-10
4      2004-03-10
          ...    
9352   2005-04-04
9353   2005-04-04
9354   2005-04-04
9355   2005-04-04
9356   2005-04-04
Name: Date, Length: 9357, dtype: datetime64[ns]

In [86]:
air_df.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0 2004-03-10  18:00:00     2.6         1360       150      11.9   
1 2004-03-10  19:00:00     2.0         1292       112       9.4   
2 2004-03-10  20:00:00     2.2         1402        88       9.0   
3 2004-03-10  21:00:00     2.2         1376        80       9.2   
4 2004-03-10  22:00:00     1.6         1272        51       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0           1046      166          1056      113          1692         1268   
1            955      103          1174       92          1559          972   
2            939      131          1140      114          1555         1074   
3            948      172          1092      122          1584         1203   
4            836      131          1205      116          1490         1110   

      T    RH      AH  
0  13.6  48.9  0.7578  
1  13.3  47.7  0.7255  
2  11.9  54.0  0.7502  
3  11.0  60.0  0.7867  
4  11.2  59.6  0.7888

In [92]:
air_df["Time"].unique()

array(['18:00:00', '19:00:00', '20:00:00', '21:00:00', '22:00:00',
       '23:00:00', '0:00:00', '1:00:00', '2:00:00', '3:00:00', '4:00:00',
       '5:00:00', '6:00:00', '7:00:00', '8:00:00', '9:00:00', '10:00:00',
       '11:00:00', '12:00:00', '13:00:00', '14:00:00', '15:00:00',
       '16:00:00', '17:00:00'], dtype=object)

In [93]:
air_df[air_df["NMHC(GT)"]==-200].count()

Date             8443
Time             8443
CO(GT)           8443
PT08.S1(CO)      8443
NMHC(GT)         8443
C6H6(GT)         8443
PT08.S2(NMHC)    8443
NOx(GT)          8443
PT08.S3(NOx)     8443
NO2(GT)          8443
PT08.S4(NO2)     8443
PT08.S5(O3)      8443
T                8443
RH               8443
AH               8443
dtype: int64

In [96]:
air_df.drop(["NMHC(GT)"],axis=1)

Date      Time  CO(GT)  PT08.S1(CO)  C6H6(GT)  PT08.S2(NMHC)  \
0    2004-03-10  18:00:00     2.6         1360      11.9           1046   
1    2004-03-10  19:00:00     2.0         1292       9.4            955   
2    2004-03-10  20:00:00     2.2         1402       9.0            939   
3    2004-03-10  21:00:00     2.2         1376       9.2            948   
4    2004-03-10  22:00:00     1.6         1272       6.5            836   
...         ...       ...     ...          ...       ...            ...   
9352 2005-04-04  10:00:00     3.1         1314      13.5           1101   
9353 2005-04-04  11:00:00     2.4         1163      11.4           1027   
9354 2005-04-04  12:00:00     2.4         1142      12.4           1063   
9355 2005-04-04  13:00:00     2.1         1003       9.5            961   
9356 2005-04-04  14:00:00     2.2         1071      11.9           1047   

      NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH  \
0         166          1056      113          1692         1268  13.6  48.9   
1         103          1174       92          1559          972  13.3  47.7   
2         131          1140      114          1555         1074  11.9  54.0   
3         172          1092      122          1584         1203  11.0  60.0   
4         131          1205      116          1490         1110  11.2  59.6   
...       ...           ...      ...           ...          ...   ...   ...   
9352      472           539      190          1374         1729  21.9  29.3   
9353      353           604      179          1264         1269  24.3  23.7   
9354      293           603      175          1241         1092  26.9  18.3   
9355      235           702      156          1041          770  28.3  13.5   
9356      265           654      168          1129          816  28.5  13.1   

          AH  
0     0.7578  
1     0.7255  
2     0.7502  
3     0.7867  
4     0.7888  
...      ...  
9352  0.7568  
9353  0.7119  
9354  0.6406  
9355  0.5139  
9356  0.5028  

[9357 rows x 14 columns]

In [98]:
air_df.count()

Date             9357
Time             9357
CO(GT)           9357
PT08.S1(CO)      9357
NMHC(GT)         9357
C6H6(GT)         9357
PT08.S2(NMHC)    9357
NOx(GT)          9357
PT08.S3(NOx)     9357
NO2(GT)          9357
PT08.S4(NO2)     9357
PT08.S5(O3)      9357
T                9357
RH               9357
AH               9357
dtype: int64

In [99]:
air_df['Time'] = pd.to_datetime(air_df['Time'], format = '%H:%M:%S')

In [100]:
air_df.head()

Date                Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0 2004-03-10 1900-01-01 18:00:00     2.6         1360       150      11.9   
1 2004-03-10 1900-01-01 19:00:00     2.0         1292       112       9.4   
2 2004-03-10 1900-01-01 20:00:00     2.2         1402        88       9.0   
3 2004-03-10 1900-01-01 21:00:00     2.2         1376        80       9.2   
4 2004-03-10 1900-01-01 22:00:00     1.6         1272        51       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0           1046      166          1056      113          1692         1268   
1            955      103          1174       92          1559          972   
2            939      131          1140      114          1555         1074   
3            948      172          1092      122          1584         1203   
4            836      131          1205      116          1490         1110   

      T    RH      AH  
0  13.6  48.9  0.7578  
1  13.3  47.7  0.7255  
2  11.9  54.0  0.7502  
3  11.0  60.0  0.7867  
4  11.2  59.6  0.7888

In [102]:
air_df.dtypes

Date             datetime64[ns]
Time             datetime64[ns]
CO(GT)                  float64
PT08.S1(CO)               int64
NMHC(GT)                  int64
C6H6(GT)                float64
PT08.S2(NMHC)             int64
NOx(GT)                   int64
PT08.S3(NOx)              int64
NO2(GT)                   int64
PT08.S4(NO2)              int64
PT08.S5(O3)               int64
T                       float64
RH                      float64
AH                      float64
dtype: object

In [104]:
year=air_df.Date.dt.year

In [108]:
print(year.head())

0    2004
1    2004
2    2004
3    2004
4    2004
Name: Date, dtype: int64


In [109]:
month=air_df.Date.dt.month

In [111]:
print(month.head(10))

0    3
1    3
2    3
3    3
4    3
5    3
6    3
7    3
8    3
9    3
Name: Date, dtype: int64


In [113]:
month.unique()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2], dtype=int64)

In [115]:
month.nunique()

12

In [117]:
day=air_df.Date.dt.day
print(day.head(8))

0    10
1    10
2    10
3    10
4    10
5    10
6    11
7    11
Name: Date, dtype: int64


In [118]:
day.nunique()

31

In [119]:
week=air_df.Date.dt.week
print(week.head())

0    11
1    11
2    11
3    11
4    11
Name: Date, dtype: int64


<ipython-input-119-36faa903d3ac>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  week=air_df.Date.dt.week


In [122]:
day_week=air_df.Date.dt.dayofweek
print(day_week.head())

0    2
1    2
2    2
3    2
4    2
Name: Date, dtype: int64


In [137]:
dayname=air_df.Date.dt.weekday_name                      #doubt

print(dayname.head())

AttributeError: 'DatetimeProperties' object has no attribute 'weekdayofname'

In [135]:
day_year=air_df.Date.dt.dayofyear
print(day_year.head())

0    70
1    70
2    70
3    70
4    70
Name: Date, dtype: int64


In [139]:
hour=air_df.Time.dt.hour
print(hour.head())


0    18
1    19
2    20
3    21
4    22
Name: Time, dtype: int64


In [140]:
hour.nunique()

24

In [144]:
minute=air_df.Time.dt.minute

In [142]:
print(minute.head())

0    0
1    0
2    0
3    0
4    0
Name: Time, dtype: int64


In [145]:
second=air_df.Time.dt.second

In [146]:
print(second.head())

0    0
1    0
2    0
3    0
4    0
Name: Time, dtype: int64


In [149]:
times=pd.to_datetime("07:00:00",format="%H:%M:%S")


In [152]:
air_df[air_df["Time"]<times].shape

(2730, 15)

In [163]:
datest=pd.to_datetime("01/01/2005",format="%d/%M/%Y")
#datestamp = pd.to_datetime("01/01/2005", format='%d/%m/%Y')

In [165]:
air_df[air_df["Date"]<datest].shape

(7134, 15)