In [2]:
list=[1,2,3,4,5]
list


[1, 2, 3, 4, 5]

In [3]:
type(list)

list

In [4]:
import numpy as np
arr=np.array(list)

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr_2d=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(arr_2d)
print(ar)
ar

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(ar)

numpy.ndarray

In [8]:
arr.shape


(5,)

In [9]:
ar.shape

(3, 3)

In [11]:
ar.ndim

2

In [12]:
arr.ndim

1

In [13]:
ar.dtype

dtype('int32')

In [14]:
arr.dtype

dtype('int32')

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((3,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [2]:
import numpy as np
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones((3,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]
arr=np.array([l1,l2,l3])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.shape

(3, 3)

In [13]:
arr
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr1=[1,2,3,4,5,6,7,8,9]
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
arr1[0]

1

In [18]:
print(arr1[1])
arr1[8]

2


9

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[:,:1]

array([[1],
       [4],
       [7]])

In [22]:
arr[:,3:]

array([], shape=(3, 0), dtype=int32)

In [23]:
arr[:,2:]

array([[3],
       [6],
       [9]])

In [24]:
arr[2:,:]

array([[7, 8, 9]])

In [25]:
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
arr1[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
arr1[2:10]

[3, 4, 5, 6, 7, 8, 9]

In [28]:
arr1[:8]

[1, 2, 3, 4, 5, 6, 7, 8]

In [29]:
arr1[8:]

[9]

In [30]:
arr1[-9:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
arr1[-9:-5]

[1, 2, 3, 4]

In [34]:
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
arr1[ :3] 

[1, 2, 3]

In [38]:
arr1[3]=100


In [39]:
arr1

[1, 2, 3, 100, 5, 6, 7, 8, 9]

In [47]:
arr1[:6]=1000   #

TypeError: can only assign an iterable

In [46]:
arr1[arr1>5]                       #


TypeError: '>' not supported between instances of 'list' and 'int'

In [48]:
l=np.array([1,2,3,4,5,6])
l

array([1, 2, 3, 4, 5, 6])

In [49]:
l[:3]=100

In [50]:
l

array([100, 100, 100,   4,   5,   6])

In [51]:
l[l>4]

array([100, 100, 100,   5,   6])

In [52]:
l[l<1]

array([], dtype=int32)

In [53]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [55]:
arr1=np.arange(1,11).reshape(5,2)
arr2=np.arange(1,11).reshape(5,2)
arr1*arr2


array([[  1,   4],
       [  9,  16],
       [ 25,  36],
       [ 49,  64],
       [ 81, 100]])

In [56]:
np.linspace(1,100,10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [63]:
np.linspace(1,1000,10)

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.random.rand(2)

array([0.26376852, 0.22751295])

In [66]:
np.random.rand(2)

array([0.32918298, 0.16327216])

In [67]:
np.random.randn(2)

array([ 0.6391084 , -0.70382505])

In [68]:
np.random.randn(2)

array([-0.64043494,  0.54587425])

In [69]:
np.random.rand(3,3)

array([[0.29015552, 0.20133584, 0.45302152],
       [0.31445347, 0.30858173, 0.44940213],
       [0.93018434, 0.27024796, 0.69743594]])

In [70]:
np.random.randn(4,4)

array([[-0.75591871,  0.46205976,  0.78898281, -0.11303872],
       [-0.50280642, -0.26180746,  1.62066806, -0.15408639],
       [ 0.18882312, -0.69653357, -1.82383986, -0.27984354],
       [-0.75019691, -0.10999387, -0.0038954 , -0.57843402]])

In [71]:
np.random.randn(4,4)

array([[-1.63921406,  0.35993851, -1.35438195, -0.36791106],
       [ 0.57226753, -0.88964423,  1.0426974 ,  0.14979946],
       [-0.24013709,  0.30533626, -0.2806809 , -0.33381322],
       [ 1.2599816 ,  1.66559597, -0.3815474 ,  0.19760216]])

In [72]:
np.random.rand(9).reshape(3,3)

array([[0.23823808, 0.50697389, 0.73523779],
       [0.52006773, 0.60962294, 0.0667494 ],
       [0.29819813, 0.84899626, 0.80132903]])

In [73]:
np.random.randn(9).reshape(3,3)

array([[-0.26927751,  0.47107027, -0.02982054],
       [ 1.1151085 ,  0.71623242,  0.53030479],
       [ 1.20480478, -0.34379461, -0.01288632]])

In [79]:
np.random.randint(3)

0

In [80]:
np.random.randint(3)

2

In [90]:
np.random.randint(3)

1

In [136]:
a=np.random.randint(0,9,2)
b=np.random.randint(0,9)
print(a)
print(b)
type(b)



[7 3]
3


int

In [137]:
type(a)

numpy.ndarray

In [107]:
np.random.randint(0,9,12)

array([5, 4, 4, 0, 2, 1, 0, 4, 7, 1, 5, 6])

In [111]:
np.random.randint(0,9,49).reshape(7,7)

array([[6, 7, 0, 6, 1, 8, 2],
       [8, 7, 7, 8, 2, 4, 5],
       [8, 0, 8, 6, 4, 1, 8],
       [6, 8, 5, 8, 2, 2, 2],
       [4, 2, 8, 6, 7, 5, 8],
       [8, 2, 4, 5, 8, 0, 7],
       [6, 5, 5, 0, 5, 3, 2]])

In [114]:
np.random.randint(1,5,10).reshape(2,5)

array([[2, 4, 4, 2, 2],
       [3, 2, 4, 3, 2]])

In [115]:
np.random.random_sample((1,5))

array([[0.76131194, 0.45990511, 0.29374217, 0.25555249, 0.56194376]])

In [128]:
np.random.random_sample((5,2))

array([[0.29211312, 0.39775274],
       [0.85127891, 0.17366905],
       [0.10059239, 0.04281231],
       [0.28680082, 0.30364472],
       [0.32954796, 0.91325086]])

In [139]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)

In [140]:
print(a)

[1 2 3 4 5 6]


In [141]:
print(b)

[[1 2 3]
 [4 5 6]]


In [142]:
a

array([1, 2, 3, 4, 5, 6])

In [143]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
a.ndim

1

In [145]:
b.ndim

2

In [146]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [147]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
arr1=np.arange(1,10)

In [149]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
arr[0]

1

In [155]:
b=arr.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [153]:
arr[1]

2

In [156]:
b[1][1]

5

In [157]:
arr[:3]=100

In [158]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [159]:
b[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [160]:
b>8

array([[ True,  True,  True],
       [False, False, False],
       [False, False,  True]])

In [161]:
b<8

array([[False, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [162]:
b

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [163]:
b[b<8]

array([4, 5, 6, 7])

In [164]:
b[b>8]

array([100, 100, 100,   9])

In [165]:
b==100

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [166]:
b

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [167]:
b.shape

(3, 3)

In [168]:
b+3

array([[103, 103, 103],
       [  7,   8,   9],
       [ 10,  11,  12]])

In [172]:
a=np.array([10,10,10])

In [173]:
a

array([10, 10, 10])

In [174]:
a+b

array([[110, 110, 110],
       [ 14,  15,  16],
       [ 17,  18,  19]])

In [175]:
a*b

array([[1000, 1000, 1000],
       [  40,   50,   60],
       [  70,   80,   90]])

In [176]:
a

array([10, 10, 10])

In [177]:
b

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [178]:
c=np.arange(0,9).reshape(3,3)

In [179]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [180]:
b+c

array([[100, 101, 102],
       [  7,   9,  11],
       [ 13,  15,  17]])

In [181]:
d=c
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [182]:
arr=np.arange(0,9)

In [183]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [184]:
arr.min()

0

In [185]:
arr.max()

8

In [186]:
arr.argmin()

0

In [187]:
arr.argmax()

8

In [188]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [189]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [190]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

In [191]:
arr.mean()

4.0

In [194]:
arr=np.arange(0,16)
arr2d=arr.reshape(4,4)

arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [195]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [196]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [197]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [198]:
arr2d.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [199]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,22,33],[44,55,66]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [200]:
c=np.concatenate((a,b),axis=1)
c

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

In [202]:
d=np.concatenate((a,b),axis=0)
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [203]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [204]:
b

array([[11, 22, 33],
       [44, 55, 66]])

In [205]:
np.hsplit(a,2)

ValueError: array split does not result in an equal division

In [206]:
c=np.arange(0,16).reshape(4,4)

In [207]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [208]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [209]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [210]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [211]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [213]:
import pandas as pd
a=pd.Series([1,2,3,4],index=["a","b","c","d"])
print(a)

a    1
b    2
c    3
d    4
dtype: int64


In [215]:
country=["INDIA","USA","ENGLAND"]
capital=["DELHI","WASHINGTON DC","LONDON"]
b=np.array(capital)
b


array(['DELHI', 'WASHINGTON DC', 'LONDON'], dtype='<U13')

In [217]:
c=pd.Series(b)
c

0            DELHI
1    WASHINGTON DC
2           LONDON
dtype: object

In [219]:
d=pd.Series(data=capital)
d

0            DELHI
1    WASHINGTON DC
2           LONDON
dtype: object

In [220]:
d=pd.Series(capital,index=country)

In [221]:
d

INDIA              DELHI
USA        WASHINGTON DC
ENGLAND           LONDON
dtype: object

In [222]:
pd.Series(data=capital,index=country)

INDIA              DELHI
USA        WASHINGTON DC
ENGLAND           LONDON
dtype: object

In [239]:
pd.Series(capital,country)

INDIA              DELHI
USA        WASHINGTON DC
ENGLAND           LONDON
dtype: object

In [242]:
b

'WASHINGTON DC'

In [225]:
pd.Series(b)

0            DELHI
1    WASHINGTON DC
2           LONDON
dtype: object

In [227]:
dic={"a":10,"b":20,"c":40,"d":40}
c=pd.Series(dic)
c

a    10
b    20
c    40
d    40
dtype: int64

In [228]:
c.shape

(4,)

In [229]:
c[1]

20

In [230]:
c[0]

10

In [232]:
c[3]

40

In [233]:
c[:2]

a    10
b    20
dtype: int64

In [234]:
c[0]

10

In [235]:
c[:]

a    10
b    20
c    40
d    40
dtype: int64

In [236]:
country

['INDIA', 'USA', 'ENGLAND']

In [237]:
country[1]

'USA'

In [238]:
country[:]

['INDIA', 'USA', 'ENGLAND']

In [243]:
c

a    10
b    20
c    40
d    40
dtype: int64

In [244]:
c["a"]

10

In [245]:
c[["a","b","c"]]

a    10
b    20
c    40
dtype: int64

In [248]:
print(c)
c+c

a    10
b    20
c    40
d    40
dtype: int64


a    20
b    40
c    80
d    80
dtype: int64

In [249]:
data={"country":["india","france","england"], "capital":["delhi","paris","london"],"population":[100,50,30]}
df=pd.DataFrame(data,columns=["country","capital","population"])


In [250]:
df

country capital  population
0    india   delhi         100
1   france   paris          50
2  england  london          30

In [258]:
c=pd.DataFrame(data)

In [260]:
c

country capital  population
0    india   delhi         100
1   france   paris          50
2  england  london          30

In [253]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [255]:
a=["apple","banana","coconut","dates"]
df=pd.DataFrame(a,columns=["fruits"])
df

fruits
0    apple
1   banana
2  coconut
3    dates

In [256]:
df=pd.DataFrame(a)
df

0
0    apple
1   banana
2  coconut
3    dates